### ISSUE TITLE
Would you mind sharing dataset with me?

### ISSUE THREAD

**Issue by xxxx231** [Ys-Jia/Vision-for-Agriculture-Competition#1]
Dear Sir/Madam,
I need Vision for Agriculture 2020 for my individual project but now I can't find this dataset anywhere. Do you still keep it? Would you mind sharing dataset with me? Thank you very much.

**Comment by Ys-Jia** [comment]
Sorry, I did not keep the dataset. I think you can refer to their website: [AGRICULTURE-VISION DATABASE](https://www.agriculture-vision.com/agriculture-vision-2021/dataset-2021) to download the 2021 dataset.
